version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
